### ISSUE TITLE
Endpoint returns Error 400 - Bad Request

### ISSUE THREAD

**Issue by JiexikaShuoMiao** [isakbm/laiout-rust-challenge#1]
Trying to get the challenge, an error is returned, additionally tested with Insomnia. 

Making GET requests to `https://dev.laiout.app/api/applicant/getChallenge` returns: 

```
{
	"error": {
		"issues": [
			{
				"code": "invalid_type",
				"expected": "object",
				"received": "string",
				"path": [],
				"message": "Expected object, received string"
			}
		],
		"name": "ZodError"
	},
	"message": "bad request"
}
```

**Comment by isakbm** [comment]
That is part of the challenge. 

The question is, which is broken, the client or the server? 😉

**Comment by JiexikaShuoMiao** [comment]
Haha! Got it.
